PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sfm: <http://onto.fel.cvut.cz/ontologies/sformsmanager#>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX form: <http://onto.fel.cvut.cz/ontologies/form/>

SELECT ?questionOrigin ?answerTextValue
WHERE {
    GRAPH <${contextUri}> {

    	?questionTemplateSnapshot sfm:hasFormTemplateVersion ?formTemplateVersion .
    	?formTemplateVersion sfm:key "${PARAMETER_1}" . # EDIT THIS

        ?questionTemplateSnapshot form:has-question-origin ?questionOrigin .
        ?questionTemplateSnapshot sfm:hasSubmittedAnswers ?answerObject .
        ?answerObject sfm:hasAnswerValue ?answerTextValue .

        FILTER NOT EXISTS {
          ?questionTemplateSnapshot sfm:hasSubmittedAnswers ?nonExistingAnswer .
          ?nonExistingAnswer sfm:hasAnswerValue ?nonExistingAnswerTextValue .

          FILTER(?nonExistingAnswerTextValue != ?answerTextValue) .
        }
    }
}