SELECT ?formGenSaveHash ?created ?modified
WHERE
{
    graph ?contextUri {
        ?s a <http://vfn.cz/ontologies/study-manager/patient-record> .
        ?s <http://purl.org/dc/terms/created> ?created
        OPTIONAL {?s <http://purl.org/dc/terms/modifed> ?modified}

        BIND (str(?s) as ?patientStr)
        BIND (md5(?patientStr) as ?formGenSaveHash)
    }
}