SELECT ?recordCreateDate ?recordModifiedDate ?remoteRecordURI ?rootQuestionOrigin
WHERE
{
    graph ?contextUri {
        ?s a <http://vfn.cz/ontologies/study-manager/patient-record> .
        ?s <http://purl.org/dc/terms/created> ?recordCreateDate .
        OPTIONAL {?s <http://purl.org/dc/terms/modified> ?recordModifiedDateOptional .}
        OPTIONAL {
            ?s <http://vfn.cz/ontologies/study-manager/has-question> ?question .
            ?question <http://onto.fel.cvut.cz/ontologies/form/has-question-origin> ?rootQuestionOrigin .
        }

        BIND(COALESCE(?recordModifiedDateOptional,?recordCreateDate) as ?recordModifiedDate)
        BIND (str(?s) as ?remoteRecordURI)
    }
}