PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sfm: <http://onto.fel.cvut.cz/ontologies/sformsmanager#>
PREFIX doc: <http://onto.fel.cvut.cz/ontologies/documentation/>
PREFIX form: <http://onto.fel.cvut.cz/ontologies/form/>

# RECORD SNAPSHOT

SELECT
    ?recordSnapshot
	?numberOfAnswers
	?key
    ?recordSnapshotCreated
    ?formTemplateVersion
	?recordVersion
    ?remoteContextUri
    ?record
WHERE {
    GRAPH <${contextUri}> {

    	?recordSnapshot a sfm:RecordSnapshot ;
  			sfm:key ?key;
			sfm:hasRemoteContextURI	?hasRemoteContextURI ;
      		sfm:hasRecord ?record ;
            sfm:recordSnapshotCreated ?recordSnapshotCreated ;
            sfm:hasNumberOfAnswers ?numberOfAnswers .

    	OPTIONAL {  }
    	OPTIONAL { ?recordSnapshot sfm:hasFormTemplateVersion	?formTemplateVersion . }
    	OPTIONAL { ?recordSnapshot sfm:hasRecordVersion ?recordVersion . }
  }
}
ORDER BY ?recordSnapshotCreated