SELECT ?formGenSaveHash ?historySaves ?lastSaved ?lastSavedContextUri
WHERE {
    {
        SELECT ?formGenSaveHash (count(?formGenSaveHash) as ?historySaves) (max(?created) as ?lastSaved)
        WHERE {
            ?x ?type <http://onto.fel.cvut.cz/ontologies/sformsmanager#FormGenMetadata> ;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#connectionName> ?connectionName;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenSaveHashCode> ?formGenSaveHash;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenCreated> ?created.
        }
        GROUP BY ?formGenSaveHash
    }
    ?b <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenCreated> ?lastSaved .
    ?b <http://onto.fel.cvut.cz/ontologies/sformsmanager#contextUri> ?lastSavedContextUri .
}