SELECT ?formGenSaveHash ?historySaves ?created ?lastModified ?lastModifiedContextUri
WHERE {
    {
        SELECT ?formGenSaveHash (count(?formGenSaveHash) as ?historySaves) (max(?modified) as ?lastModified)
        WHERE {
            ?x ?type <http://onto.fel.cvut.cz/ontologies/sformsmanager#FormGenMetadata> ;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#connectionName> ?connectionName;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenSaveHashCode> ?formGenSaveHash;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenModified> ?modified .

        }
        GROUP BY ?formGenSaveHash
    }

    ?b <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenModified> ?lastModified .
    ?b <http://onto.fel.cvut.cz/ontologies/sformsmanager#formGenCreated> ?created .
    ?b <http://onto.fel.cvut.cz/ontologies/sformsmanager#contextUri> ?lastModifiedContextUri .
}