SELECT (year(xsd:dateTime(?earliestDate)) as ?earliestYear) (month(xsd:dateTime(?earliestDate)) as ?earliestMonth) (year(xsd:dateTime(?latestDate)) as ?latestYear) (month(xsd:dateTime(?latestDate)) as ?latestMonth)
WHERE
{
    SELECT (min(?created) as ?earliestDate) (max(?created) as ?latestDate)
    WHERE {
        GRAPH ?contextUri {
            ?x ?type <http://onto.fel.cvut.cz/ontologies/sformsmanager#RecordSnapshot> ;
                <http://onto.fel.cvut.cz/ontologies/sformsmanager#recordSnapshotCreated> ?created ;
        }
  }
}