SELECT ?versionKeyOrInternalName ?year ?month (count(*) as ?count)
WHERE {
    GRAPH ?contextUri {
        ?x ?type <http://onto.fel.cvut.cz/ontologies/sformsmanager#RecordSnapshot> ;
            <http://onto.fel.cvut.cz/ontologies/sformsmanager#recordSnapshotCreated> ?snapshotCreated ;
            <http://onto.fel.cvut.cz/ontologies/sformsmanager#hasFormTemplateVersion> ?vObject .
  		?vObject <http://onto.fel.cvut.cz/ontologies/sformsmanager#key> ?versionKey .
		OPTIONAL { ?vObject <http://onto.fel.cvut.cz/ontologies/sformsmanager#internalName> ?versionInternalName . }

  		BIND(COALESCE(?versionInternalName, ?versionKey) as ?versionKeyOrInternalName)
        BIND ( year(xsd:dateTime(?snapshotCreated)) as ?year )
        BIND ( month(xsd:dateTime(?snapshotCreated)) as ?month )
    }
}
GROUP BY ?versionKeyOrInternalName ?year ?month